### ISSUE TITLE
#97 로그인 토큰 유효기간 변경 & jwt secret yml & 프론트 요청에 따른 로그인 로직 추가 및 변경

### ISSUE THREAD

**Issue by Byun-Sung-Ho** [UMC-AboutMe/AboutMe-BE#97]
## 📝 개요
- 로그인 토큰 유효기간 변경 & jwt secret yml로 변경

## ✔️ To-Do
- [ ] 로그인 토큰 유효기간 변경
- [ ] jwt secret yml로 변경
- [ ] accessToken으로 받은 이메일 정보를 파라미터로 하는 로그인 로직 추가

## 👀 ETC
-
